#!/usr/bin/env bash

type jo >/dev/null 2>&1 || {
  echo >&2 "Error: jo cli must be installed (try brew install jo)"
  usage
  exit 1
}

for i in {1..100}
do
   jo foo=bar n="${i}" baz=1.5 >> test.jsonl
done